version: '3.8'

services:

  mongo:
    image: mongo:7
    container_name: veda-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis:7-alpine
    container_name: veda-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  backend:
    container_name: veda-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb+srv://pratyusht2006_db_user:SWDiiQm75K36k0uo@cluster0.mhjh04i.mongodb.net/?appName=Cluster0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_MODEL: ${GROQ_MODEL}
    depends_on:
      - mongo
      - redis
    volumes:
      - ./backend/uploads:/app/uploads  # persist uploaded files

  frontend:
    container_name: veda-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_WS_URL: ws://localhost:5000
      API_URL: http://backend:5000   # server-side fetch uses container name
    depends_on:
      - backend

volumes:
  mongo-data:
  redis-data: